# -------------------------------------------------------------------------------------
# Menu Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------

[[main]]
identifier = "collections"
pre = ""
post = ""
name = "Collections"
url = "/collections/"
title = ""
weight = 1

[main.params]
icon = "fa-solid fa-layer-group"

[[main]]
identifier = "archives"
pre = ""
post = ""
name = "Archives"
url = "/archives/"
title = ""
weight = 2

[main.params]
icon = "fa-solid fa-box-archive"

[[main]]
identifier = "categories"
pre = ""
post = ""
name = "Categories"
url = "/categories/"
title = ""
weight = 3

[main.params]
icon = "fa-solid fa-folder-tree"

[[main]]
identifier = "tags"
pre = ""
post = ""
name = "Tags"
url = "/tags/"
title = ""
weight = 4

[main.params]
icon = "fa-solid fa-tags"

[[main]]
identifier = "about"
pre = ""
post = ""
name = "About"
url = "/about/"
title = ""
weight = 5

[main.params]
icon = "fa-solid fa-circle-info"
