# -------------------------------------------------------------------------------------
# Modules Configuration
# See: https://gohugo.io/configuration/module/
# -------------------------------------------------------------------------------------

[[imports]]
path = "github.com/hugo-fixit/FixIt"

[[imports]]
path = "github.com/hugo-fixit/cmpt-flyfish"

[[imports]]
path = "github.com/hugo-fixit/cmpt-mdevtools"

[[imports]]
path = "github.com/hugo-fixit/cmpt-santa-hat"

[[imports]]
path = "github.com/hugo-fixit/cmpt-translate"

[[imports]]
path = "github.com/hugo-fixit/hugo-json-feed"

[[imports]]
path = "github.com/hugo-fixit/shortcode-asciinema"

[[imports]]
path = "github.com/hugo-fixit/shortcode-caniuse"

[[imports]]
path = "github.com/hugo-fixit/shortcode-docs-bookmark"

[[imports]]
path = "github.com/hugo-fixit/shortcode-mmt-netease"

[[imports]]
path = "github.com/Artexxx/cmpt-post-preview"
version = "latest"

[hugoVersion]
extended = true
min = "0.156.0"
