# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/configuration/all/
# -------------------------------------------------------------------------------------

baseURL = "https://nfl-alvis.github.io/ctf-writeups/"
